### ISSUE TITLE
if I activate the http through a class and I think a centralized service does not work in the server model

### ISSUE THREAD

**Issue by carlosalcantara2668** [Suchiman/BlazorDualMode#1]
I did a service to centralize the http, but when changing from the client model to the server, it simply does not work.

![image](https://user-images.githubusercontent.com/16179281/46961182-36d97100-d06e-11e8-8e5f-c8fbcc874e94.png)

![image](https://user-images.githubusercontent.com/16179281/46961186-3a6cf800-d06e-11e8-94d8-21c8ed848e36.png)

![image](https://user-images.githubusercontent.com/16179281/46961193-3d67e880-d06e-11e8-8735-1c0698c31736.png)

**Comment by Suchiman** [comment]
"does not work" isn't an appropriate error description. Any exceptions? What do you see that makes you think it doesn't work?
Did you take care of step 2 of the howto? Be extra careful to register the HttpClient inside the Startup.cs of the Client Project: https://github.com/Suchiman/BlazorDualMode/blob/853b2ec3d4b3ac028c365d593265e932912f02ff/BlazorDualMode.Client/Startup.cs

**Comment by carlosalcantara2668** [comment]
if you register it, if you perform the exercise of creating a service to center http calls and change to the server model, it simply does not respond.

if the call is direct within the page if you are working very well in the server model.

Please try to make the call of the http on the FetchData page through a registered service.

![image](https://user-images.githubusercontent.com/16179281/46962269-b9633000-d070-11e8-9f2f-545c7ef39aa6.png)

**Comment by carlosalcantara2668** [comment]
Please forgive my writing in English.
that I am new studying the language.

**Comment by Suchiman** [comment]
@carlosalcantara2668 i see, try using `AddScoped` instead of `AddSingleton`, that works for me.
The reason is that Blazors `IUriHelper` is a `Scoped` service hence `HttpClient` must be scoped and so does `ServiceArticulo`. The problem is that a singleton service (longer lifetime) cannot resolve a scoped service (shorter lifetime).

**Comment by carlosalcantara2668** [comment]
@Suchiman now it's working, this is perfect, thank you very much.
