### ISSUE TITLE
Razor Components and Blazor 0.8.0

### ISSUE THREAD

**Issue by simonziegler** [Suchiman/BlazorDualMode#2]
Hi Robin,

Your Dual Mode demonstration proved very, very helpful to me late last year. Now that Blazor Serverside has been split to Razor Components in ASP.NET Core 3.0 and Blazor 0.8.0 is out, will you have an opportunity to reapply your dual mode work to the current status?

Thanks!

**Comment by GiroSA** [comment]
Yes, please keep this updated for latest versions until MS implements this.

**Comment by Suchiman** [comment]
I've did some experimenting and so far i didn't manage to get this going again. If any of you find a way, i'm open to PR's 😉

**Comment by Suchiman** [comment]
As of 3.0 preview 6 this is possible again, i've updated the repo to reflect that!
