### ISSUE TITLE
Identify the browser webassembly support and pass the query string

### ISSUE THREAD

**Issue by sowsan** [Suchiman/BlazorDualMode#3]
Is there a way to check the browser support for webassembly on the blazor app and load the corresponding type server or client using the work-around u have?

**Comment by Suchiman** [comment]
@sowsan most certainly, use a check like in https://stackoverflow.com/questions/47879864/how-can-i-check-if-a-browser-supports-webassembly and then use the result of that to decide on which mode (javascript file) you want to load
