### ISSUE TITLE
Not working with the release of 3.0

### ISSUE THREAD

**Issue by acotterell1973** [Suchiman/BlazorDualMode#6]
Hi Robin, 
I love this project and solve a problem we had. However, with the update of 3.0. This doesn't seem to work anymore. I just see the loading screen when trying with server mode enable.  Any guidance with this?

**Comment by Suchiman** [comment]
Resolved with https://github.com/Suchiman/BlazorDualMode/commit/fad4a6c934a1e69703e1d81ad254465176f227f1
