### ISSUE TITLE
endpoints.MapBlazorHub<T>("app") instead of endpoints.MapBlazorHub() causing error

### ISSUE THREAD

**Issue by shahriarhossain** [Suchiman/BlazorDualMode#9]
With the release of .NET Core 3 , now we can't do the following steps:
**_endpoints.MapBlazorHub<Client.App>("app")_**
Instead we need to call   **_endpoints.MapBlazorHub();_**

Need help resolving this.

**Comment by Suchiman** [comment]
Sorry, the instructions in the README are still a bit out of date.
Check this commit https://github.com/Suchiman/BlazorDualMode/commit/fad4a6c934a1e69703e1d81ad254465176f227f1

**Comment by shahriarhossain** [comment]
Thanks. Issue resolved.
